import Head from 'next/head';
import React from 'react';
import Comics from 'components/Comics';
import { GetServerSideProps } from 'next/types';
import md5 from 'md5';

export interface Comic {
  id: number;
  title: string;
  sprite: { path: string; extension: string };
}

export const getServerSideProps: GetServerSideProps = async () => {
  const offsetOptions = [0, 100, 200, 300, 400, 500];
  const offset =
    offsetOptions[Math.floor(Math.random() * offsetOptions.length)];

  const ts = Math.floor(Date.now() / 1000);
  const hash = md5(ts + process.env.PRIVATE_KEY + process.env.PUBLIC_KEY);

  const res = await fetch(
    `https://gateway.marvel.com:443/v1/public/comics?limit=100&offset=${offset}&ts=${ts}&apikey=${process.env.PUBLIC_KEY}&hash=${hash}`
  );
  const comics = await res.json();

  const shuffled = comics.data.results.sort(() => 0.5 - Math.random());

  return {
    props: {
      data: shuffled.slice(0, 5).map((item) => {
        return { id: item.id, title: item.title, sprite: item.thumbnail };
      }),
    },
  };
};

export default function Home({ data }: { data: Comic[] }) {
  return (
    <div>
      <Head>
        <title>5 Random Comics</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Comics comics={data} />
    </div>
  );
}
