import Head from 'next/head';
import React from 'react';
import Comics from 'components/Comics';
import { GetServerSideProps } from 'next/types';
import md5 from 'md5';
import { getRandomInt } from 'utils';

export interface Comic {
  id: number;
  title: string;
  sprite: { path: string; extension: string };
}

export const getServerSideProps: GetServerSideProps = async () => {
  const offset = getRandomInt(0, 800);

  const ts = Math.floor(Date.now() / 1000);
  const hash = md5(ts + process.env.PRIVATE_KEY + process.env.PUBLIC_KEY);

  const res = await fetch(
    `https://gateway.marvel.com:443/v1/public/comics?limit=5&offset=${offset}&ts=${ts}&apikey=${process.env.PUBLIC_KEY}&hash=${hash}`
  );
  const comics = await res.json();

  return {
    props: {
      data: comics.data.results.map((item) => {
        return { id: item.id, title: item.title, sprite: item.thumbnail };
      }),
    },
  };
};

export default function Home({ data }: { data: Comic[] }) {
  return (
    <div>
      <Head>
        <title>5 Random Comics</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Comics comics={data} />
    </div>
  );
}
